version: "3.8"
services:
  app:
    image: hello-front-dev
    build:
      context: ./
      dockerfile: dev.Dockerfile
    command: ["npm", "run", "dev", "--", "--host"]
    ports:
      - "5173:5173"
    volumes:
      - "./:/usr/src/app"
      - node_modules:/usr/src/app/node_modules
    restart: "no"
  
volumes:
  node_modules: