version: "3.8"

services:
  todo-frontend:
    image: todo-frontend-prod
    build:
      context: ./todo-frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    restart: always
    environment:
      - VITE_BACKEND_URL=http://todo-backend:3000/api
    depends_on:
      - todo-backend

  nginx:
    image: nginx:1.20.1
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    container_name: reverse-proxy
    depends_on:
      - todo-frontend
      - todo-backend

  mongo:
    image: mongo
    ports:
      - "3456:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: the_database
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  todo-backend:
    image: todo-backend-prod
    build:
      context: ./todo-backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - REDIS_URL=redis://redis:6379
      - MONGO_URL=mongodb://the_username:the_password@mongo:27017/the_database
    volumes:
      - ./todo-backend:/usr/src/app
    depends_on:
      - mongo
      - redis

volumes:
  mongo_data:
  redis_data:
