version: '3.8'

services:
  app:
    build: .
    ports:
      - 3000:3000
    environment:
      MONGO_URL: mongodb://mongo:27017/todos
      REDIS_URL: redis://redis:6379
  mongo:
    image: mongo
  redis:
    image: redis
