version: "3.8"

services:
  frontend:
    image: blogapp-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 5173:80
    container_name: blogapp-frontend-prod

  nginx:
    image: nginx:1.20.1
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro 
      - ./frontend/dist:/usr/share/nginx/html
    ports:
      - 8080:80 
    depends_on:
      - frontend
      - backend

  backend:
    image: blogapp-backend-prod
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - MONGODB_URI=mongodb+srv://samw0907:EadDuryan1706%21@atlascluster.fjk6ysb.mongodb.net/bloglistApp?retryWrites=true&w=majority
      - NODE_ENV=production
    ports:
      - 3003:3003
    container_name: blogapp-backend-prod
